// Rasterises each house sigil's charge (art/sigils/<house>.svg, <g id="charge">) into a low-resolution mask in
// headless Chromium, so the house monuments carry the real sigil art. The masks are written to
// art/sculptures/src/sigil-masks.json and committed, so building sculptures needs no browser.
// Mask rows run top to bottom; '#' is the charge, '+' is dark engraving inside the charge, '.' is empty.
import fs from 'node:fs';
import path from 'node:path';
import { ART, loadModule, innerGroup } from '../lib.mjs';
import { HOUSE_KEYS_ORDER } from './palette.mjs';

export const MASKS_FILE = path.join(ART, 'sculptures', 'src', 'sigil-masks.json');

/** The SVG of a sigil's charge alone, framed on its 200 x 200 box. */
export function chargeSvg(house) {
  const svg = fs.readFileSync(path.join(ART, 'sigils', `${house}.svg`), 'utf8');
  const defs = (svg.match(/<defs>[\s\S]*?<\/defs>/) || [''])[0];
  const g = innerGroup(svg, 'charge');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="28 28 200 200" width="400" height="400">${defs}${g.startTag}${g.inner}</g></svg>`;
}

/** Turns per-cell coverage and brightness into mask rows. */
export function classify(cells, res, { cover = 0.42, dark = 0.3 } = {}) {
  const rows = [];
  for (let y = 0; y < res; y++) {
    let line = '';
    for (let x = 0; x < res; x++) {
      const c = cells[y * res + x];
      line += c.cover < cover ? '.' : c.lum < dark ? '+' : '#';
    }
    rows.push(line);
  }
  return rows;
}

export async function buildMasks(resolutions = [12, 16, 20]) {
  const { chromium } = await loadModule('playwright');
  const exe = process.env.PLAYWRIGHT_CHROMIUM || (fs.existsSync('/opt/pw-browsers/chromium') ? '/opt/pw-browsers/chromium' : undefined);
  const browser = await chromium.launch(exe ? { executablePath: exe } : {});
  const out = { note: 'Generated by node art/tools/sculptor/cli.mjs masks from art/sigils/*.svg. Do not edit.', masks: {} };
  try {
    const page = await browser.newPage();
    for (const house of HOUSE_KEYS_ORDER) {
      out.masks[house] = {};
      const url = `data:image/svg+xml;base64,${Buffer.from(chargeSvg(house)).toString('base64')}`;
      for (const res of resolutions) {
        const cells = await page.evaluate(async ({ url, res }) => {
          const img = new Image();
          img.src = url;
          await img.decode();
          const N = 400;
          const cv = document.createElement('canvas');
          cv.width = N; cv.height = N;
          const ctx = cv.getContext('2d');
          ctx.drawImage(img, 0, 0, N, N);
          const px = ctx.getImageData(0, 0, N, N).data;
          const out = [];
          const step = N / res;
          for (let cy = 0; cy < res; cy++) for (let cx = 0; cx < res; cx++) {
            let a = 0, l = 0, n = 0;
            for (let y = Math.floor(cy * step); y < Math.floor((cy + 1) * step); y++)
              for (let x = Math.floor(cx * step); x < Math.floor((cx + 1) * step); x++) {
                const i = (y * N + x) * 4, al = px[i + 3] / 255;
                a += al; l += al * (0.2126 * px[i] + 0.7152 * px[i + 1] + 0.0722 * px[i + 2]) / 255; n++;
              }
            out.push({ cover: a / n, lum: a > 0 ? l / a : 0 });
          }
          return out;
        }, { url, res });
        out.masks[house][res] = classify(cells, res);
      }
    }
  } finally {
    await browser.close();
  }
  fs.writeFileSync(MASKS_FILE, JSON.stringify(out, null, 1) + '\n');
  return out;
}

export function readMasks() {
  if (!fs.existsSync(MASKS_FILE)) throw new Error('art/sculptures/src/sigil-masks.json is missing: run node art/tools/sculptor/cli.mjs masks');
  return JSON.parse(fs.readFileSync(MASKS_FILE, 'utf8')).masks;
}
