// Outlines the Realm wordmark from Cinzel (SIL Open Font License 1.1) into plain SVG path data,
// so the logo renders identically everywhere without the font installed.
//
//   node art/tools/wordmark.mjs --bold <Cinzel-Bold.ttf> --semibold <Cinzel-SemiBold.ttf>
//
// Writes art/src/wordmark.json. Run it only when the wordmark lettering changes; the output is committed.
// The font files are NOT committed: fetch them from Google Fonts (Cinzel, weights 600 and 700).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadModule } from './lib.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const args = Object.fromEntries(process.argv.slice(2).reduce((a, v, i, all) => (v.startsWith('--') ? a.concat([[v.slice(2), all[i + 1]]]) : a), []));
if (!args.bold || !args.semibold) {
  console.error('usage: node art/tools/wordmark.mjs --bold Cinzel-Bold.ttf --semibold Cinzel-SemiBold.ttf');
  process.exit(2);
}
const opentype = (await loadModule('opentype.js')).default;

// Serialises opentype commands, dropping zero-length line segments (the font has many, and they
// trip svgo's path optimiser). One decimal is plenty at this size.
function pathData(commands) {
  const f = (v) => String(+v.toFixed(1));
  let out = '', cx = null, cy = null, sx = null, sy = null;
  for (const c of commands) {
    if (c.type === 'M') { out += `M${f(c.x)} ${f(c.y)}`; cx = sx = c.x; cy = sy = c.y; }
    else if (c.type === 'L') { if (f(c.x) === f(cx) && f(c.y) === f(cy)) continue; out += `L${f(c.x)} ${f(c.y)}`; cx = c.x; cy = c.y; }
    else if (c.type === 'Q') { out += `Q${f(c.x1)} ${f(c.y1)} ${f(c.x)} ${f(c.y)}`; cx = c.x; cy = c.y; }
    else if (c.type === 'C') { out += `C${f(c.x1)} ${f(c.y1)} ${f(c.x2)} ${f(c.y2)} ${f(c.x)} ${f(c.y)}`; cx = c.x; cy = c.y; }
    else if (c.type === 'Z') { out += 'Z'; cx = sx; cy = sy; }
  }
  return out;
}

// Lays out `text` at `size` with extra tracking (in em), returns path data normalised so the cap box starts at 0,0.
function outline(fontFile, text, size, tracking) {
  const buf = fs.readFileSync(fontFile);
  const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
  const scale = size / font.unitsPerEm;
  const capHeight = (font.tables.os2 && font.tables.os2.sCapHeight) || font.charToGlyph('H').getBoundingBox().y2;
  let x = 0;
  const parts = [];
  const glyphs = font.stringToGlyphs(text);
  glyphs.forEach((g, i) => {
    parts.push(pathData(g.getPath(x, capHeight * scale, size).commands));
    x += g.advanceWidth * scale + (i < glyphs.length - 1 ? tracking * size : 0);
    if (i < glyphs.length - 1) x += font.getKerningValue(g, glyphs[i + 1]) * scale;
  });
  const p = new opentype.Path();
  // Measure the real ink box so lockups can align on ink, not on advance widths.
  glyphs.reduce((xx, g, i) => {
    const gp = g.getPath(xx, capHeight * scale, size);
    p.extend(gp);
    return xx + g.advanceWidth * scale + (i < glyphs.length - 1 ? tracking * size + font.getKerningValue(g, glyphs[i + 1]) * scale : 0);
  }, 0);
  const bb = p.getBoundingBox();
  return {
    text, font: path.basename(fontFile), size, tracking,
    d: parts.join(''),
    ink: { x: +bb.x1.toFixed(1), y: +bb.y1.toFixed(1), w: +(bb.x2 - bb.x1).toFixed(1), h: +(bb.y2 - bb.y1).toFixed(1) },
    capHeight: +(capHeight * scale).toFixed(1),
  };
}

const out = {
  note: 'Generated by art/tools/wordmark.mjs from Cinzel (OFL 1.1). Do not edit by hand.',
  realm: outline(args.bold, 'REALM', 120, 0.12),
  ostreval: outline(args.semibold, 'OSTREVAL', 30, 0.42),
};
fs.writeFileSync(path.join(here, '..', 'src', 'wordmark.json'), JSON.stringify(out, null, 2) + '\n');

// Advance widths of Cinzel Bold (in em) so social-card titles can be wrapped by width, not by character count.
{
  const buf = fs.readFileSync(args.bold);
  const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
  const chars = " ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.,;:'’\"“”!?-–—&()/…";
  const widths = {};
  for (const ch of chars) widths[ch] = +(font.charToGlyph(ch).advanceWidth / font.unitsPerEm).toFixed(3);
  fs.writeFileSync(path.join(here, '..', 'src', 'cinzel-bold-widths.json'), JSON.stringify({ note: 'Generated by art/tools/wordmark.mjs from Cinzel Bold (OFL 1.1). Advance widths in em.', fallback: 0.75, widths }, null, 2) + '\n');
  console.log('wrote art/src/cinzel-bold-widths.json');
}
console.log('wrote art/src/wordmark.json', out.realm.ink, out.ostreval.ink);
